### ISSUE TITLE
When using b b or b p it is not adding at the correct nested level

### ISSUE THREAD

**Issue by WesHoward** [KerfuffleV2/logseq-plugin-blocknav#1]
Indent should always match the selected block. It is not. Currently it is at the leftmost (top) indent level

New block should be adjacent to the selected block. It is not, it is adding to the first and last blocks on the page.

Given the following

- block 1
   - nest 1
   - nest 2
- block 2

If I am on nest 1 and use b p it inserts a new block above block 1 and b b inserts below block 2. It should be a block adjacent to nest 1 with the proper level of indentation.

If I use b b with block 1 selected it is inserting below block 2 when it should be inserting betwee block 1 and block 2 at the same level of indent.

**Comment by KerfuffleV2** [comment]
I seem to recall there actually wasn't a way to accomplish what you're talking about (at least I couldn't find it). I haven't really done anything with Logseq plugins for 5-6 months so the details of the API aren't really fresh in my mind, also it's possible the plugin API has been extended.

Anyway, this is why I have it described as a "*simple plugin to facilitate* ***top-level*** *block navigation*" in the `README`.

**Comment by KerfuffleV2** [comment]
I'm going to close this for now since the creator didn't respond. @ me if you want to continue discussion.
