### ISSUE TITLE
README describes 'b e' to edit last block in page - but config file has it set as 'b l'

### ISSUE THREAD

**Issue by da-** [KerfuffleV2/logseq-plugin-blocknav#2]
Unless I'm missing something, there's a difference in the docs and implementation. The docs should say `b l` to edit the last block, shouldn't it?
Thanks for the plugin; it scratches an itch I've had for keyboard shortcuts since I started with logseq a few months ago.

**Comment by KerfuffleV2** [comment]
You're completely correct! Good catch. Should be fixed now.

I'm glad you're finding the plugin useful!
